#ifndef ATED_H
#define ATED_H

#define IWPRIV_ERROR								(0)
#define IWPRIV_OK									(1)

#define SOCK_MAX_LISTEN								5
#define CMD_MAXLEN									1024
#define PWR_ARRAY_LEN 								13

#define SIOCIWFIRSTPRIV								(0x8BE0)

#define RTPRIV_IOCTL_E2P        					(SIOCIWFIRSTPRIV + 0x07)
#define RTPRIV_IOCTL_ATE							(SIOCIWFIRSTPRIV + 0x08)
#define RTPRIV_IOCTL_STATISTICS                     (SIOCIWFIRSTPRIV + 0x09)

#define RTPRIV_IOCTL_ATE_SET						0x779
#define RTPRIV_IOCTL_ATE_EFUSE_WRITEBACK			0x765
#define RTPRIV_IOCTL_ATE_WRITECAL					0x766
#define RTPRIV_IOCTL_ATE_SET_DA						0x767
#define RTPRIV_IOCTL_ATE_SET_SA						0x768
#define RTPRIV_IOCTL_ATE_SET_BSSID					0x769
#define RTPRIV_IOCTL_ATE_SET_TX_ANT					0x76A
#define RTPRIV_IOCTL_ATE_SET_TX_CHANNEL				0x76B
#define RTPRIV_IOCTL_ATE_SET_TX_MODE				0x76C
#define RTPRIV_IOCTL_ATE_SET_TX_MCS					0x76D
#define RTPRIV_IOCTL_ATE_SET_TX_BW					0x76E
#define RTPRIV_IOCTL_ATE_SET_TX_GI					0x76F
#define RTPRIV_IOCTL_ATE_SET_TX_LENGTH				0x770
#define RTPRIV_IOCTL_ATE_SET_TX_POW0				0x771
#define RTPRIV_IOCTL_ATE_SET_TX_POW1				0x772
#define RTPRIV_IOCTL_ATE_SET_TX_COUNT				0x773
#define RTPRIV_IOCTL_ATE_SET_TX_FREQOFFSET			0x774
#define RTPRIV_IOCTL_ATE_SET_RX_ANT					0x775
#define RTPRIV_IOCTL_ATE_SET_RX_FER					0x776
#define RTPRIV_IOCTL_ATE_SET_RESETCOUNTER			0x777
#define RTPRIV_IOCTL_ATE_EFUSE_LOAD					0x778
#define RTPRIV_IOCTL_ATE_AUTO_ALC					0x77A
#define RTPRIV_IOCTL_ATE_VCO_CAL					0x77B


#endif /* ATED_H */

