# Automatically generated by configure - do not modify!
VERSION=
PREFIX=/usr/local
prefix=$(DESTDIR)$(PREFIX)
libdir=$(DESTDIR)$(PREFIX)/lib
includedir=$(DESTDIR)$(PREFIX)/include
MAKE=make
CC=$(TOOLPREFIX)gcc
AR=$(TOOLPREFIX)ar
RANLIB=$(TOOLPREFIX)ranlib
BUILD_STATIC=yes
BUILD_SHARED=no
LN=ln
STRIP=$(TOOLPREFIX)strip
INSTALLSTRIP=-s
INSTALL=/usr/bin/install -c
DEBUG=no
