# Automatically generated by configure - do not modify!
VERSION=1.1a
PREFIX=/usr/local
prefix=$(DESTDIR)$(PREFIX)
bindir=$(DESTDIR)${PREFIX}/bin
sysconfdir=$(DESTDIR)${PREFIX}/etc
localedir=$(DESTDIR)${PREFIX}/share/locale
MAKE=make
CC=$(TOOLPREFIX)gcc
LN=ln
STRIP=$(TOOLPREFIX)strip
INSTALLSTRIP=-s
INSTALL=/usr/bin/install -c
DEBUG=no

OPTFLAGS=-W -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -O3 -DHAVE_LOCALE_H -DHAVE_SETLOCALE -DHAVE_LANGINFO_H -DHAVE_LANGINFO_CODESET -DHAVE_DLNA

OPTFLAGS+=-D__LINUX_OS_FC__ -fstrength-reduce -fomit-frame-pointer
